// let b = 2


try {

    let a = 2 + b

} catch(e) {

    console.log(e)
    //trhow new Error(e)

}

console.log("Teste")